Haulmont/jmix-frontend

packages/jmix-react-core/src/app/MainStore.ts
(cherry picked from commit 8e371096abb66bead60799efd2192cc1feb070cf)
=> fix: login form not shown when session expires #350

packages/jmix-react-core/src/util/metadata.ts, packages/jmix-react-ui/src/ui/form/CharInput.less, packages/jmix-react-ui/src/ui/form/CharInput.tsx, packages/jmix-react-ui/src/ui/form/Form.tsx, packages/jmix-react-ui/src/ui/table/DataTableCustomFilter.tsx, packages/jmix-react-ui/src/ui/table/DataTableListEditor.tsx, packages/jmix-rest/src/model.ts
=> feat: implemented supporting of char datatype

CONTRIBUTING.md, DEVELOPMENT.md
=> docs(Front Generator): improved development process description

packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json, packages/jmix-react-ui/package-lock.json, packages/jmix-react-ui/package.json
=> fix: fix antd error message templates

example-react-app/package-lock.json, example-react-app/package.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json, packages/jmix-react-ui/package-lock.json, packages/jmix-react-ui/package.json, packages/jmix-react-ui/src/ui/table/DataTable.tsx, packages/jmix-react-ui/src/ui/table/DataTableCustomFilter.tsx, packages/jmix-react-ui/src/ui/table/DataTableHelpers.tsx, packages/jmix-react-ui/src/ui/table/DataTableIntervalEditor.tsx, packages/jmix-react-ui/src/ui/table/DataTableListEditor.tsx
BREAKING CHANGE:
antd version was updated to 4.12.3
=> chore: update antd version to 4.12.3

packages/jmix-front-generator/src/generators/react-typescript/entity-cards/template/EntityCards.tsx.ejs, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-cards/MpgFavoriteCarCards.tsx
=> fix: entity cards template does not handle non-updatable entities correctly

packages/jmix-rest/src/jmix.ts, packages/jmix-rest/test/jmix-rest-connection.spec.js
=> refactor: updated url to revoke endpoint #157

example-react-app/package-lock.json, example-react-app/package.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json, packages/jmix-react-core/package-lock.json, packages/jmix-react-core/package.json, packages/jmix-react-ui/package-lock.json, packages/jmix-react-ui/package.json
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-core, @haulmont/jmix-react-ui
BREAKING CHANGE:
update mobx-react version to 7.1.0
=> chore: update mobx-react version to 7.1.0 #168

packages/jmix-front-generator/CHANGELOG.md, packages/jmix-front-generator/package-lock.json, packages/jmix-front-generator/package.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json, packages/jmix-front-generator/src/generators/react-typescript/entity-management/answers.ts, packages/jmix-react-core/CHANGELOG.md, packages/jmix-react-core/package-lock.json, packages/jmix-react-core/package.json, packages/jmix-react-ui/CHANGELOG.md, packages/jmix-react-ui/package-lock.json, packages/jmix-react-ui/package.json, packages/jmix-rest/CHANGELOG.md, packages/jmix-rest/package-lock.json, packages/jmix-rest/package.json
=> fix: fixed issue with string id questions #179

packages/jmix-front-generator/src/generators/react-typescript/entity-cards/answers.ts
=> fix: fixed issue with string id questions in entity-cards generator #181

packages/jmix-react-core/src/data/Instance.test.tsx, packages/jmix-react-core/src/util/formats.ts, packages/jmix-react-ui/src/ui/table/DataTableIntervalFunctions.test.ts
=> fix: updated date formats #186

packages/jmix-front-generator/src/building-blocks/pipelines/defaultPipeline.ts, packages/jmix-front-generator/src/generators/react-typescript/app/write.ts
=> fix: fixed issue with wrong execute directory on generate sdk stage #197

example-react-app/package-lock.json, example-react-app/src/app/car-cards-grid/CarCardsGrid.tsx, example-react-app/src/app/datatypes-test-cards/DatatypesCards.tsx, example-react-app/src/app/entity-cards/FavoriteCars.tsx, example-react-app/src/app/int-id-cards/IntIdentityIdCards.tsx, example-react-app/src/i18n/en.json, example-react-app/src/routing.ts, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/menu.ts, packages/jmix-front-generator/src/generators/react-typescript/blank-component/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/index.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/options.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/template/EntityCardsGrid.tsx.ejs, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-management/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-management/write.ts, packages/jmix-front-generator/src/test/fixtures/answers.json, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-cards-grid/MpgFavoriteCarCardsGrid.tsx, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-cards/MpgFavoriteCarCards.tsx, packages/jmix-front-generator/src/test/generators/react-typrscript/react-generator.test.ts, packages/jmix-front-generator/src/test/init.test.ts, packages/jmix-react-ui/src/ui/paging/Paging.tsx, scripts/generate-example-react-app.js, scripts/screens/car-cards-grid.json
=> feat: entity cards grid template

example-react-app/package-lock.json, example-react-app/package.json, packages/jmix-front-generator/package-lock.json, packages/jmix-front-generator/package.json, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/sdk/model/entities-generation.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json, packages/jmix-react-core/package-lock.json, packages/jmix-react-core/package.json, packages/jmix-react-ui/package-lock.json, packages/jmix-react-ui/package.json, packages/jmix-rest/package-lock.json, packages/jmix-rest/package.json, packages/react-ide-toolbox/package-lock.json, packages/react-ide-toolbox/package.json
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-core, @haulmont/jmix-react-ui,
@haulmont/jmix-rest, @haulmont/react-ide-toolbox
BREAKING CHANGE:
updated typescript version
=> fix: fixed installing issue with npm7 #220

example-react-app/src/app/structure/StructureComponent.tsx, example-react-app/src/i18n/en.json, example-react-app/src/routing.ts, packages/jmix-front-generator/src/building-blocks/stages/template-model/defaultDeriveTemplateModel.ts, packages/jmix-front-generator/src/generators/react-typescript/structure/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/structure/index.ts, packages/jmix-front-generator/src/generators/react-typescript/structure/options.ts, packages/jmix-front-generator/src/generators/react-typescript/structure/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/structure/template/ColunmLayout.tsx.ejs, packages/jmix-front-generator/src/generators/react-typescript/structure/write.ts, packages/jmix-front-generator/src/test/fixtures/answers.json, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/component/StructureComponent.tsx, packages/jmix-front-generator/src/test/generators/react-typrscript/react-generator.test.ts, scripts/generate-example-react-app.js, scripts/screens/structure.json
=> feat: structure template

example-react-app/package-lock.json, example-react-app/package.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json
=> feat: updated react-scripth with implemented highlighting dev modes #212

packages/jmix-front-generator/test/e2e/e2e-common.js, packages/react-ide-toolbox/src/previews/previews.tsx
affects: @haulmont/react-ide-toolbox
=> fix: fixed issue with empty preview children #264

example-react-app/src/dev/palette.tsx, packages/jmix-front-generator/package-lock.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/dev/palette.tsx, packages/react-ide-toolbox/src/index.ts, packages/react-ide-toolbox/src/palette/palette.tsx
affects: @haulmont/jmix-front-generator, @haulmont/react-ide-toolbox
refs  #270
=> feat: basic components palette in react app template

example-react-app/src/app/App.tsx, example-react-app/src/app/AppMenu.tsx, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/menu.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/App.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/AppMenu.tsx, packages/jmix-front-generator/src/generators/react-typescript/blank-component/write.ts, packages/jmix-front-generator/src/generators/react-typescript/common/menu.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-management/write.ts, packages/jmix-front-generator/src/generators/react-typescript/structure/write.ts, packages/jmix-react-ui/jest.config.js, packages/jmix-react-ui/src/index.ts, packages/jmix-react-ui/src/mocks/test-mocks/styleMock.ts, packages/jmix-react-ui/src/ui/menu/horizontal-menu/HorizontalMenu.test.tsx, packages/jmix-react-ui/src/ui/menu/horizontal-menu/HorizontalMenu.tsx, packages/jmix-react-ui/src/ui/menu/horizontal-menu/index.ts, packages/jmix-react-ui/src/ui/menu/index.ts, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.test.tsx, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.tsx, packages/jmix-react-ui/src/ui/menu/menu-item/index.ts, packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.test.tsx, packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.tsx, packages/jmix-react-ui/src/ui/menu/sub-menu-item/index.ts, packages/jmix-react-ui/src/ui/menu/vertical-menu/VerticalMenu.test.tsx, packages/jmix-react-ui/src/ui/menu/vertical-menu/VerticalMenu.tsx, packages/jmix-react-ui/src/ui/menu/vertical-menu/index.ts
antd menu components were wrapped into custom components and taken out in ui package
implemented generation menu component on write stage
=> feat: declarative menu creation #22

packages/jmix-react-core/src/index.ts, packages/jmix-react-core/src/timer/index.ts, packages/jmix-react-core/src/timer/timer.test.tsx, packages/jmix-react-core/src/timer/timer.ts
=> feat: implemented hook timer #217

example-react-app/src/app/AppMenu.tsx, packages/jmix-front-generator/package-lock.json, packages/jmix-front-generator/package.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/AppMenu.tsx, packages/jmix-front-generator/src/generators/react-typescript/common/menu.ts, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.tsx, packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.tsx
=> fix: issues with menu after antd updating #321

example-react-app/src/app/AppMenu.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/AppMenu.tsx, packages/jmix-front-generator/src/generators/react-typescript/common/menu.ts, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.tsx
=> feat: using title property to set MenuItem label #325

packages/jmix-react-core/src/conditional-rendering/IF.test.tsx, packages/jmix-react-core/src/conditional-rendering/IF.tsx, packages/jmix-react-core/src/conditional-rendering/index.ts, packages/jmix-react-core/src/index.ts
=> feat: implementend IF component #218

packages/jmix-react-core/src/timer/timer.ts
=> fix: jsdoc for useTimer hook #315

example-react-app/src/index.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/index.tsx.ejs, packages/jmix-react-core/src/app/JmixAppProvider.tsx, packages/jmix-react-core/src/app/MainStore.test.ts, packages/jmix-react-core/src/app/MainStore.ts, packages/jmix-react-core/src/app/Security.test.ts, packages/jmix-react-core/src/app/Security.ts
=> refactor: replace rest with gql

packages/jmix-react-ui/src/ui/menu/horizontal-menu/HorizontalMenu.test.tsx, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.test.tsx, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.tsx, packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.test.tsx, packages/jmix-react-ui/src/ui/menu/vertical-menu/VerticalMenu.test.tsx
=> feat: behavior of caption property in MenuItem #344

packages/jmix-react-ui/src/ui/menu/horizontal-menu/HorizontalMenu.test.tsx, packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.test.tsx, packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.tsx, packages/jmix-react-ui/src/ui/menu/vertical-menu/VerticalMenu.test.tsx
=> feat: caption property to SubMenuItem #340

example-react-app/src/app/AppMenu.tsx, packages/jmix-react-ui/src/ui/table/DataTable.tsx
=> chore: disable sorting on relation fields

example-react-app/package.json, packages/jmix-react-core/src/data/Instance.tsx, packages/jmix-react-ui/src/crud/editor/form/useAntdForm.ts, packages/jmix-react-ui/src/formatters/jmixFront_to_ant.ts
Commit 40930ffd contains the fix, the other two commits contain some refactoring of the formatter.
=> fix: deleted O2O Composition still shows in the editor

example-react-app/src/dev/previews.tsx, packages/jmix-front-generator/src/generators/react-typescript/common/previews-registartion.ts, packages/jmix-front-generator/src/test/generators/react-typrscript/common/previews-registartion.test.ts
=> feat: using AST in previews generation #358

packages/jmix-react-core/jest.config.js, packages/jmix-react-core/src/app/JmixAppProvider.tsx, packages/jmix-react-core/src/data/Instance.test.tsx, packages/jmix-react-core/src/data/Instance.tsx, packages/jmix-react-core/src/data/PropertyType.ts, packages/jmix-react-core/src/util/formats.ts, packages/jmix-react-core/src/util/metadata.ts, packages/jmix-react-core/src/util/normalizeMetadata.ts, packages/jmix-react-ui/src/ui/form/Form.tsx, packages/jmix-react-ui/src/ui/table/DataTable.tsx, packages/jmix-react-ui/src/ui/table/DataTableCell.tsx, packages/jmix-react-ui/src/ui/table/DataTableCustomFilter.tsx, packages/jmix-react-ui/src/ui/table/DataTableIntervalEditor.tsx, packages/jmix-react-ui/src/ui/table/DataTableIntervalFunctions.test.ts, packages/jmix-react-ui/src/ui/table/DataTableIntervalFunctions.ts, packages/jmix-react-ui/src/ui/table/DataTableListEditor.tsx, packages/jmix-react-ui/src/util/formatting.test.ts, packages/jmix-react-ui/src/util/formatting.ts, packages/jmix-rest/src/model.ts
affects: @haulmont/jmix-react-core, @haulmont/jmix-react-ui, @haulmont/jmix-rest
=> fix: missing filters in the table #354

example-react-app/package.json, packages/jmix-react-core/src/app/Apollo.ts
=> fix: permissions are not re-requested upon relogin #375

example-react-app/src/app/datatypes-test-browser-cards/DatatypesTestBrowserCards.tsx, example-react-app/src/app/datatypes-test-browser-list/DatatypesTestBrowserList.tsx, example-react-app/src/app/datatypes-test-browser-table/DatatypesTestBrowserTable.tsx, example-react-app/src/app/datatypes-test-cards/DatatypesTestCards.tsx, example-react-app/src/app/datatypes-test-editor/DatatypesTestEditor.tsx, example-react-app/src/jmix/entities/scr_DatatypesTestEntity.ts, example-react-app/src/jmix/metadata.json, packages/jmix-react-core/src/data/PropertyType.ts, packages/jmix-react-core/src/util/metadata.ts, packages/jmix-react-ui/src/ui/form/Form.tsx, packages/jmix-react-ui/src/ui/table/DataTableCustomFilter.tsx, packages/jmix-react-ui/src/ui/table/DataTableListEditor.tsx, scripts/model/graphql/datatypesTestEntity.js, scripts/model/projectModel-scr-jmix.json
=> fix: missing filter for Character attribute #354

example-react-app/package.json, example-react-app/src/app/App.tsx, example-react-app/src/app/AppMenu.tsx, example-react-app/src/app/header/AppHeader.css, example-react-app/src/app/header/AppHeader.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/app/index.ts, packages/jmix-front-generator/src/generators/react-typescript/app/options.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/App.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/AppMenu.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/header/AppHeader.css, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/header/AppHeader.tsx, packages/jmix-react-core/package-lock.json, packages/jmix-react-ui/package-lock.json, scripts/generate-example-react-app.js, scripts/model/example-react-app-answers.js
=> feat: app horizontal menu

example-react-app/src/app/car-browser-cards/CarBrowserCards.tsx, example-react-app/src/app/car-browser-list/CarBrowserList.tsx, example-react-app/src/app/car-browser-table/CarBrowserTable.tsx, example-react-app/src/app/car-cards-grid/CarCardsGrid.tsx, example-react-app/src/app/car-editor/CarEditor.tsx, example-react-app/src/app/car-master-detail/CarMasterDetail.tsx, example-react-app/src/app/car-master-detail/CarMasterDetailBrowser.tsx, example-react-app/src/app/car-master-detail/CarMasterDetailEditor.tsx, example-react-app/src/app/entity-cards/FavoriteCars.tsx, example-react-app/src/jmix/entities/ScrUserInfo.ts, example-react-app/src/jmix/entities/scr_Car.ts, example-react-app/src/jmix/entities/scr_CarRent.ts, example-react-app/src/jmix/entities/scr_FavoriteCar.ts, example-react-app/src/jmix/entities/scr_Garage.ts, example-react-app/src/jmix/entities/scr_Product.ts, example-react-app/src/jmix/entities/scr_SparePart.ts, example-react-app/src/jmix/entities/scr_TechnicalCertificate.ts, example-react-app/src/jmix/metadata.json, packages/jmix-react-core/src/app/Security.ts, packages/jmix-server-mock/src/index.ts, packages/jmix-server-mock/src/mocks.ts, scripts/model/example-react-app-answers.js, scripts/model/projectModel-scr-jmix.json, scripts/model/scr-jmix-schema.graphql
affects: @haulmont/jmix-react-core, @haulmont/jmix-server-mock
=> feat: mocked permissions for mock-server #385

packages/jmix-react-ui/src/screen-registration/screen-registration.tsx
=> fix: editor is opened twice when editing from registered entity list

example-react-app/package.json, example-react-app/src/app/AppMenu.tsx, packages/jmix-react-ui/src/ui/notifications/Notifications.test.tsx, packages/jmix-react-ui/src/ui/notifications/Notifications.tsx
=> refactor: notifications API #436

packages/jmix-react-ui/src/screen-registration/screen-registration.tsx
=> revert: partially revert Fix render DOM elements inside tabs

example-react-app/src/app/car-master-detail/CarMasterDetailBrowser.tsx, example-react-app/src/app/car-master-detail/CarMasterDetailEditor.tsx, example-react-app/src/routing.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/template/EntityEditor.tsx.ejs, packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/template/Table.tsx.ejs
=> fix: master-detail screen: incorrect route after pagination #446

packages/jmix-react-core/src/app/Tabs.ts
=> fix: error after closing first active tab

example-react-app/package.json, example-react-app/src/app/App.tsx, example-react-app/src/app/AppMenu.tsx, example-react-app/src/app/example-custom-screen/ExampleCustomScreen.tsx, example-react-app/src/app/home/HomePage.tsx, example-react-app/src/dev/previews.tsx, example-react-app/src/i18n/en.json, example-react-app/src/routing.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/App.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/AppMenu.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/home/HomePage.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/routing.ts, packages/jmix-react-core/src/app/ContentDisplayMode.ts, packages/jmix-react-core/src/app/JmixAppProvider.tsx, packages/jmix-react-core/src/app/MainStore.ts, packages/jmix-react-core/src/app/Tabs.test.ts, packages/jmix-react-core/src/app/Tabs.ts, packages/jmix-react-core/src/index.ts, packages/jmix-react-ui/src/index.ts, packages/jmix-react-ui/src/screen-registration/screen-registration.test.tsx, packages/jmix-react-ui/src/screen-registration/screen-registration.tsx, packages/jmix-react-ui/src/ui/Tabs/index.tsx, packages/jmix-react-ui/src/ui/content-area/ContentArea.tsx, packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.tsx, packages/jmix-react-ui/src/ui/single-content-area/SingleContentArea.tsx, packages/jmix-react-ui/src/ui/single-content-area/SingleContentAreaState.ts, scripts/custom-screens/ExampleCustomScreen.tsx, scripts/generate-client-scr.js, scripts/generate-example-react-app.js, scripts/model/example-react-app-answers.js
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-core, @haulmont/jmix-react-ui
=> feat: switchable tabbing modes #452

test-pup/example-react-app/blank-screen.test.js, test-pup/example-react-app/car-browse-cards-paging.test.js, test-pup/example-react-app/car-browse-components.test.js, test-pup/example-react-app/car-browse-list-paging.test.js, test-pup/example-react-app/car-cards-grid-component.test.js, test-pup/example-react-app/car-cards-grid-paging.test.js, test-pup/example-react-app/car-editor-security.test.js, test-pup/example-react-app/car-master-detail-component.test.js, test-pup/example-react-app/car-master-detail-paging.test.js, test-pup/example-react-app/car-master-detail-security.test.js, test-pup/example-react-app/data-table/data-table-custom-filter/FilterActions.js, test-pup/example-react-app/structure.test.js
=> WIP: revive e2e (puppeteer) tests for all template

example-react-app/src/app/AppMenu.tsx, example-react-app/src/app/associationM2M-management/AssociationM2MEditor.tsx, example-react-app/src/app/associationM2O-management/AssociationM2OEditor.tsx, example-react-app/src/app/associationO2M-management/AssociationO2MEditor.tsx, example-react-app/src/app/associationO2O-management/AssociationO2OEditor.tsx, example-react-app/src/app/boring-string-id-editor/BoringStringIdEditor.tsx, example-react-app/src/app/car-editor/CarEditor.tsx, example-react-app/src/app/compositionO2M-management/CompositionO2MEditor.tsx, example-react-app/src/app/compositionO2O-management/CompositionO2OEditor.tsx, example-react-app/src/app/datatypes-test-editor/DatatypesTestEditor.tsx, example-react-app/src/app/deeplyNestedO2M-editor/DeeplyNestedO2MTestEntityEditor.tsx, example-react-app/src/app/deeplyNestedO2O-editor/DeeplyNestedTestEntityEditor.tsx, example-react-app/src/app/int-id-editor/IntIdEditor.tsx, example-react-app/src/app/int-identity-id-editer/IntIdentityIdEditor.tsx, example-react-app/src/app/string-id-editor/StringIdMgtCardsEdit.tsx, example-react-app/src/app/tricky-id-editor/TrickyIdEditor.tsx, example-react-app/src/app/weird-string-id-editor/WeirdStringIdEditor.tsx, packages/jmix-front-generator/src/generators/react-typescript/entity-editor/template/EntityEditor.tsx.ejs, packages/jmix-front-generator/src/generators/react-typescript/entity-editor/write.ts
=> fix: adding generated edit components to app menu and routes

test-pup/example-react-app/car-browse-components.test.js, test-pup/example-react-app/car-editor-security.test.js, test-pup/example-react-app/cat-editor-component.test.js
=> test: e2e tests for browse-table and entity-editor #469

packages/jmix-react-core/src/app/Screens.ts, packages/jmix-react-core/src/app/Tabs.ts
=> fix: route is not changed when switching/closing tabs #404

packages/jmix-react-ui/src/formatters/jmixFront_to_ant.ts
=> fix: dates are not shown in editor fields #480

packages/jmix-react-ui/src/ui/table/DataTable.less, packages/jmix-react-ui/src/ui/table/DataTable.tsx
[Table looks weird when there is only one column #312](https://app.zenhub.com/workspaces/jmix-frontend-issues-5fe0992a4308f20011f1c913/issues/haulmont/jmix-frontend/312)
=> Table looks weird when there is only one column #312

example-react-app/src/jmix/metadata.json, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/sdk/sdk.ts, packages/jmix-react-core/src/app/MetadataProvider.tsx, packages/jmix-react-core/src/data/Instance.test.tsx, packages/jmix-react-core/src/util/normalizeMetadata.ts
=> feat: app persistentEntity flag for entity to metadata

packages/jmix-react-core/src/app/Screens.ts
=> fix: checking currentScreen and currentRootPageData to null value #522

packages/jmix-react-ui/src/crud/list/ui-callbacks/usePaginationChangeCallback.ts
=> fix: checking currentScreen to null value #521

packages/jmix-react-ui/src/index.ts, packages/jmix-react-ui/src/ui/form/Form.tsx
=> feat: exporting some things to implementing DataTools addon #520

packages/jmix-react-core/src/app/Tabs.tsx, packages/jmix-react-ui/src/ui/Tabs/index.tsx, packages/jmix-react-ui/src/util/screen.tsx
=> fix: cancel btn without parent screen

example-react-app/src/jmix/metadata.json, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/sdk/sdk.ts, packages/jmix-react-core/src/app/MetadataProvider.tsx, packages/jmix-react-core/src/data/Instance.test.tsx, packages/jmix-react-core/src/util/normalizeMetadata.ts
=> feat: add idAttributeName field to entites metadata #539

packages/jmix-front-generator/test/e2e/react-client--new-project.test.js
=> test: temporary disable failed integration test

test-pup/example-react-app/car-browse-cards-paging.test.js, test-pup/example-react-app/car-browse-list-paging.test.js, test-pup/example-react-app/car-cards-grid-component.test.js, test-pup/example-react-app/car-cards-grid-paging.test.js, test-pup/example-react-app/car-editor-security.test.js, test-pup/example-react-app/car-master-detail-paging.test.js, test-pup/example-react-app/car-master-detail-security.test.js
=> test: prepare e2e tests to run on Teamcity

packages/jmix-server-mock/package-lock.json, packages/jmix-server-mock/package.json
affects: @haulmont/jmix-server-mock
=> chore: add graphql to @haulmont/jmix-server-mock dependencies #557

packages/jmix-front-generator/package-lock.json, packages/jmix-front-generator/src/building-blocks/stages/answers/pieces/defaultAnswers.ts, packages/jmix-front-generator/src/common/studio/studio-model.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-browser/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-editor/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-management/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-multi-selection-table/answers.ts
=> feat: add info about step to questions

example-react-app/src/i18n/en.json, example-react-app/src/i18n/ru.json, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/i18n.ts, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/menu.ts, packages/jmix-front-generator/src/generators/react-typescript/addon/index.ts, packages/jmix-front-generator/src/generators/react-typescript/addon/options.ts, packages/jmix-front-generator/src/generators/react-typescript/addon/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/addon/write.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/zh-cn.json, packages/jmix-front-generator/src/generators/react-typescript/common/menu.ts, packages/jmix-front-generator/src/test/generators/react-typrscript/common/i18n.test.ts, packages/jmix-front-generator/src/test/generators/react-typrscript/common/menu.test.ts, packages/jmix-front-generator/src/test/init.test.ts
=> feat: implement addon generator #513

packages/jmix-front-generator/src/generators/react-typescript/entity-cards-with-details/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-with-details/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-table-with-filters/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-table-with-filters/template-model.ts
=> fix: replace some import paths after moving entity.ts

example-react-app/package.json, example-react-app/src/app/car-master-detail/CarMasterDetailEditor.tsx, packages/jmix-front-generator/src/building-blocks/includes/Fields.ejs, packages/jmix-front-generator/src/generators/react-typescript/entity-editor/template/EntityEditor.tsx.ejs, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/template/FormWizard.tsx.ejs, packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/template/EntityEditor.tsx.ejs, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/MasterDetail/MasterDetailStore.ts, packages/jmix-react-antd/src/ui/MasterDetail/useChangeConfirm.ts, packages/jmix-react-antd/src/ui/MasterDetail/useMasterDetailEditor.tsx, packages/jmix-react-antd/src/ui/MasterDetail/useMasterDetailList.ts, scripts/update-client-libs.js, scripts/update-react-client-libs.js
Add confirm windows for master-detail (#408)
=> feat: add confirm windows for master detail #408

packages/jmix-react-web/src/crud/list/ui-callbacks/usePaginationChangeCallback.ts, packages/jmix-react-web/src/crud/list/useEntityList.ts
=> fix: list screen rows per page dropdown #548

packages/jmix-react-web/src/ui/Tabs/Content.tsx
=> fix: fix navigating with browser history #588

example-react-app/src/dev/palette.tsx, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/palette.ts, packages/jmix-front-generator/src/generators/react-typescript/blank-screen/write.ts, packages/jmix-front-generator/src/generators/react-typescript/common/previews-registartion.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-browser/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-grid/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards-with-details/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-cards/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-editor/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-multi-selection-table/write.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-table-with-filters/write.ts, packages/jmix-front-generator/src/index.ts, packages/jmix-front-generator/src/test/generators/react-typrscript/common/palette.test.ts
=> feat: register screens in palette #460

example-react-app/src/index.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/index.tsx.ejs, packages/jmix-front-generator/src/test/fixtures/react-client/src/index.tsx, packages/jmix-react-antd/src/util/history.test.ts, packages/jmix-react-core/src/app/Router.tsx, packages/jmix-react-core/src/app/Screens.test.ts, packages/jmix-react-core/src/app/Screens.ts, packages/jmix-react-core/src/app/Tabs.test.ts, packages/jmix-react-web/src/index.ts, packages/jmix-react-web/src/ui/IntlDocumentTitle.tsx, packages/jmix-react-web/src/util/screen.tsx
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-antd, @haulmont/jmix-react-core,
@haulmont/jmix-react-web
=> fix: navigation improvements #587 #590

packages/jmix-react-antd/src/formatters/ant_to_jmixFront.ts, packages/jmix-react-antd/src/ui/form/Form.tsx, packages/jmix-react-core/src/app/MetadataProvider.tsx, packages/jmix-react-core/src/util/metadata.ts, packages/jmix-react-core/src/util/normalizeMetadata.ts
affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-core
=> fix: ignore embedded fields

packages/jmix-react-antd/src/formatters/ant_to_jmixFront.ts
updating entity containing property associated with integer id entity #638
=> fix: updating entity containing property associated with integer id entity #638

packages/jmix-react-antd/src/formatters/ant_to_jmixFront.ts, packages/jmix-react-core/src/util/data.ts, packages/jmix-react-core/src/util/metadata.ts, packages/jmix-rest/src/jmix.ts, packages/jmix-rest/src/util.ts
affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-core, @haulmont/jmix-rest
=> refactor: add EntityId union #638

example-react-app/package.json, example-react-app/src/app/datatypes-calendar/DatatypesCalendar.tsx, packages/jmix-front-generator/src/generators/react-typescript/entity-calendar/template/EntityCalendar.tsx.ejs, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/Calendar/CalendarHeader.tsx
=> fix: replace CalendareHeader on custom

example-react-app/package.json, packages/jmix-react-antd/src/ui/MasterDetail/useMasterDetailList.ts
=> fix: add confirm on unselect to master-detail

packages/jmix-react-core/src/app/Security.ts
=> fix: permissions query #614

example-react-app/package.json, example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/TimeField.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/time-field.test.js, test-pup/package-lock.json, test-pup/package.json
=> feat: add TimeField form control

example-react-app/package.json, example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/DateField.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/date-field.test.js
=> feat: add datefield form control

example-react-app/src/app/App.test.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/App.test.tsx
=> fix: App.test.tsx #746

packages/jmix-react-antd/src/ui/form/controls/TextArea.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/text-area-field.test.js
=> feat: add TextArea form control

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/SliderField.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/slider-field.test.js
=> feat: add Slider form control #709

example-react-app/src/app/form-wizard-editor/FormWizardEditor.tsx, example-react-app/src/i18n/en.json, example-react-app/src/i18n/ru.json, packages/jmix-front-generator/src/common/studio/studio-model.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/zh_cn.json, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/template/FormWizard.tsx.ejs, packages/jmix-front-generator/src/test/generators/react-typrscript/common/i18n.test.ts, packages/jmix-front-generator/src/test/generators/react-typrscript/entity-form-wizard/template-model.test.ts, packages/jmix-react-antd/src/ui/FormWizard/FormWizardManager.tsx, packages/jmix-react-antd/src/ui/FormWizard/FormWizardStep.tsx, packages/jmix-react-antd/src/ui/FormWizard/FormWizardStepStatus.tsx, packages/jmix-react-antd/src/ui/FormWizard/useEntityEditorFormWizard.tsx, scripts/screens/form-wizard-editor.js
make wizard steps studio field Int type instead hard configuration array
=> fix: simplify wizard steps studio field

packages/jmix-front-generator/src/generators/react-typescript/entity-browser/template/Table.tsx.ejs, packages/jmix-react-core/src/crud/getRelationOptions.ts, packages/jmix-react-core/src/crud/useEntityEditorData.ts
=> fix: add form relation options, list generation #719

packages/jmix-react-web/src/i18n/LocalesStore.test.tsx
=> test: i18n parametrization #551

example-react-app/src/index.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/index.tsx.ejs, packages/jmix-front-generator/src/test/fixtures/react-client/src/index.tsx, packages/jmix-react-core/package.json, packages/jmix-react-core/src/app/Apollo.ts, packages/jmix-react-core/src/app/JmixAppProvider.tsx, packages/jmix-react-core/src/app/MainStore.ts, packages/jmix-react-core/src/app/Security.ts, packages/jmix-react-core/src/app/useGetFile.ts, packages/jmix-react-core/src/index.ts, packages/jmix-react-core/src/util/security.ts, packages/jmix-react-ui/src/formatters/jmixFront_to_ant.ts, packages/jmix-react-ui/src/ui/FileUpload.tsx
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-core, @haulmont/jmix-react-ui
=> feat: graphql file upload/download #614

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/form/controls/base/JmixFormFieldProps.ts, packages/jmix-react-antd/src/ui/form/controls/base/JmixFormFieldWrapper.tsx, packages/jmix-react-antd/src/ui/form/entity-form/EntityForm.tsx, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/entity-form.test.js
=> feat: add EntityForm component #636

packages/jmix-front-generator/src/building-blocks/stages/answers/pieces/refineAnswers.ts, scripts/screens/form-wizard-editor.js
=> chore: parse integer fields from serialised answers

test-pup/example-react-app/form-wizard.test.js
=> test: fix form-wizard e2e tests

example-react-app/package.json, example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, example-react-app/src/dev/palette.tsx, example-react-app/src/dev/previews.tsx, example-react-app/src/i18n/en.json, example-react-app/src/routing.ts, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/EntityHierarchyTree/EntityHierachyTree.tsx, packages/jmix-react-antd/src/ui/EntityHierarchyTree/index.ts, scripts/custom-screens/CustomDataDisplayComponents.tsx, scripts/generate-example-react-app.js, scripts/model/example-react-app-answers.js, test-pup/example-react-app/entity-hierarchy-tree.test.js
=> feat: add data display component: EntityHierarchyTree #696

packages/jmix-react-antd/src/formatters/jmixFront_to_ant.ts
=> fix: _instanceName attribute for compositions #779

packages/jmix-front-generator/src/building-blocks/stages/answers/pieces/stringId.ts, packages/jmix-front-generator/src/common/studio/studio-model.ts, packages/jmix-front-generator/src/generators/react-typescript/app/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/common/questions.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-calendar/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/answers.ts
=> refactor: add type options for attribute StudioTemplateProperty

packages/jmix-react-antd/src/ui/menu/addons-menu/AddonsMenu.tsx, packages/jmix-react-web/src/ui/Menu/MenuStore.tsx
affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-web
=> fix: issue with several menu items from addons #795

example-react-app/package.json, example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, package-lock.json, packages/jmix-react-web/src/index.ts, packages/jmix-react-web/src/ui/Label.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx, test-pup/example-react-app/label.test.js, test-pup/package-lock.json
=> feat: add data display component: label

example-react-app/package.json, example-react-app/src/app/AppMenu.tsx, example-react-app/src/app/custom-app-layouts/CustomAppLayouts.module.css, example-react-app/src/app/custom-app-layouts/CustomAppLayouts.tsx, example-react-app/src/dev/palette.tsx, example-react-app/src/dev/previews.tsx, example-react-app/src/i18n/en.json, example-react-app/src/routing.ts, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/layouts/AppLayout.tsx, packages/jmix-react-antd/src/ui/layouts/Content.tsx, packages/jmix-react-antd/src/ui/layouts/Footer.tsx, packages/jmix-react-antd/src/ui/layouts/Header.tsx, packages/jmix-react-antd/src/ui/layouts/Sider.tsx, packages/jmix-react-antd/src/ui/layouts/index.ts, scripts/custom-screens/CustomAppLayouts.module.css, scripts/custom-screens/CustomAppLayouts.tsx, scripts/generate-example-react-app.js, scripts/model/example-react-app-answers.js, test-pup/example-react-app/layouts.test.ts
=> feat: add data display components: app layouts

example-react-app/package.json, example-react-app/src/app/datatypes-calendar/DatatypesCalendar.tsx, packages/jmix-front-generator/src/generators/react-typescript/entity-calendar/answers.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-calendar/template-model.ts, packages/jmix-front-generator/src/generators/react-typescript/entity-calendar/template/EntityCalendar.tsx.ejs, scripts/screens/datatypes-calendar.js
=> chore: fix some typos in calendar template

packages/jmix-addon-charts/.gitignore, packages/jmix-addon-charts/README.md, packages/jmix-addon-charts/package-lock.json, packages/jmix-addon-charts/package.json, packages/jmix-addon-charts/rollup.config.js, packages/jmix-addon-charts/src/component/BarChart.tsx, packages/jmix-addon-charts/src/component/LineChart.tsx, packages/jmix-addon-charts/src/component/PieChart.tsx, packages/jmix-addon-charts/src/component/default-chart-options.ts, packages/jmix-addon-charts/src/index.ts, packages/jmix-addon-charts/tsconfig.json
affects: @haulmont/jmix-addon-charts
=> feat: chart addon

scripts/custom-screens/CustomFormControls.tsx
=> fix: fix SliderField tooltip #797

example-react-app/src/app/custom-app-layouts/CustomAppLayouts.tsx, packages/jmix-react-antd/src/ui/layouts/Sidebar.tsx, packages/jmix-react-antd/src/ui/layouts/index.ts, scripts/custom-screens/CustomAppLayouts.tsx, test-pup/example-react-app/layouts.test.ts
=> fix: rename sider to Sidebar & separate renders tests #692

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/SelectField.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/select-field.test.js
=> feat: add SelectField form control #705

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/package.json, packages/jmix-react-antd/src/ui/form/controls/SourceCodeField.module.less, packages/jmix-react-antd/src/ui/form/controls/SourceCodeField.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/source-code-editor.test.js
=> feat: add SourceCodeEditor form control #714

example-react-app/package.json, example-react-app/src/app/car-multi-selection-table/CarMultiSelectionTable.tsx, packages/jmix-front-generator/src/generators/react-typescript/entity-multi-selection-table/template/MultiSelectionTable.tsx.ejs
=> fix: do not hide selection column in multi-select table

packages/jmix-react-core/src/app/Router.tsx, packages/jmix-react-core/src/app/Screens.test.ts, packages/jmix-react-core/src/app/Screens.ts, packages/jmix-react-core/src/app/Tabs.test.ts, packages/jmix-react-ui/src/crud/list/useEntityList.ts, packages/jmix-react-ui/src/ui/Tabs/index.tsx, packages/jmix-react-ui/src/util/history.test.ts, packages/jmix-react-ui/src/util/history.ts, packages/jmix-react-ui/src/util/screen.tsx
=> fix: hash routing, url reflect only root screen state (hotfix)

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/RadioButton.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/radio-button.test.js
=> feat: add RadioButton form control #707

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/DropdownField.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/dropdown-field.test.js
=> feat: add DropdownField form control #812

example-react-app/src/jmix/metadata.json, packages/jmix-addon-data-tools/src/entity-inspector/entity-data-editor/fields/Fields.tsx, packages/jmix-addon-data-tools/src/entity-inspector/entity-data-viewer/EntityDataViewer.tsx, packages/jmix-addon-data-tools/src/entity-inspector/entityRestore.ts, packages/jmix-addon-data-tools/src/entity-inspector/gqlQueryGeneration.ts, packages/jmix-addon-data-tools/src/i18n/en.json, packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/sdk/sdk.ts, packages/jmix-react-core/src/app/MetadataProvider.tsx, packages/jmix-react-core/src/util/normalizeMetadata.ts, packages/jmix-react-web/src/index.ts
affects: @haulmont/jmix-addon-data-tools, @haulmont/jmix-front-generator, @haulmont/jmix-react-core,
@haulmont/jmix-react-web
=> fix: several issues in data-tools addon #825

packages/jmix-react-antd/src/ui/form/Form.tsx, packages/jmix-react-antd/src/ui/table/DataTableCell.tsx, packages/jmix-react-antd/src/ui/table/DataTableHelpers.tsx, packages/jmix-react-core/src/app/MainStore.ts, packages/jmix-react-core/src/util/metadata.ts, packages/jmix-react-core/src/util/normalizeMetadata.ts, packages/jmix-react-web/src/ui/entity-property/EntityProperty.tsx
affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-core, @haulmont/jmix-react-web
=> fix: enum localization #788

example-react-app/src/app/AppErrorBoundary.tsx, example-react-app/src/app/AppMenu.tsx, example-react-app/src/app/error-boundary-tests/ErrorBoundaryTests.tsx, example-react-app/src/dev/palette.tsx, example-react-app/src/dev/previews.tsx, example-react-app/src/i18n/en.json, example-react-app/src/index.tsx, example-react-app/src/routing.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/AppErrorBoundary.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/index.tsx, packages/jmix-front-generator/src/test/fixtures/react-client/src/index.tsx, packages/jmix-react-antd/package-lock.json, packages/jmix-react-web/src/ui/MultiScreen/MultiScreen.tsx, scripts/custom-screens/ErrorBoundaryTests.tsx, scripts/generate-example-react-app.js, scripts/model/example-react-app-answers.js, test-pup/example-react-app/app-error-boundary.test.js, test-pup/example-react-app/multi-screen-error-boundary.test.ts
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-web, test-puppeteer
=> test: add tests to app and screen level boundaries #803

packages/jmix-front-generator/src/generators/react-typescript/entity-browser/template/Table.tsx.ejs, packages/jmix-react-core/src/crud/getRelationOptions.ts, packages/jmix-react-core/src/crud/useEntityEditorData.test.tsx, packages/jmix-react-core/src/crud/useEntityEditorData.ts
=> fix: support self-referencing associations #719

example-react-app/package.json, example-react-app/src/app/AppMenu.tsx, example-react-app/src/app/custom-controls/CustomControls.tsx, example-react-app/src/dev/palette.tsx, example-react-app/src/dev/previews.tsx, example-react-app/src/i18n/en.json, example-react-app/src/routing.ts, scripts/custom-screens/CustomControls.tsx, scripts/generate-example-react-app.js, scripts/model/example-react-app-answers.js, test-pup/example-react-app/paging.test.js
=> test: add test for Paging component

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/tooltip/Tooltip.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx, test-pup/example-react-app/tooltip.test.js
=> feat: add Tooltip #700

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/progress-bar/ProgressBar.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx, test-pup/example-react-app/progress-bar.test.js
=> feat: add ProgressBar #699

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/Card/Card.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx, test-pup/example-react-app/card.test.js
=> chore: added CustomCard component #694 

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, packages/jmix-react-antd/src/ui/EntityHierarchyTree/EntityHierachyTree.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx
=> fix: typeError on explicitly set parentId to undefined #696

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.module.css, example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, packages/jmix-react-antd/src/index.ts, packages/jmix-react-antd/src/ui/Grid/Col/Col.tsx, packages/jmix-react-antd/src/ui/Grid/Row/Row.tsx, packages/jmix-react-antd/src/ui/Grid/index.ts, scripts/custom-screens/CustomDataDisplayComponents.module.css, scripts/custom-screens/CustomDataDisplayComponents.tsx, scripts/generate-example-react-app.js, test-pup/example-react-app/grid.test.js
=> chore: added Row and Col components #691

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx, test-pup/example-react-app/data-table.test.js
=> test: add e2e test for DataTable

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, packages/jmix-react-antd/src/ui/form/controls/Button.tsx, packages/jmix-react-antd/src/ui/form/controls/index.ts, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/form-controls/button.test.js
=> chore: add Button #708

packages/jmix-front-generator/src/common/model/cuba-model.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/zh_cn.json, packages/jmix-front-generator/src/test/generators/react-typrscript/common/i18n.test.ts, packages/jmix-react-core/src/app/MetadataProvider.tsx, packages/jmix-react-core/src/crud/validation.ts
=> fix: client validation, support length rule #744

test-pup/example-react-app/tabs.test.js
=> chore: added test for MultiTabs component #693

example-react-app/package.json, example-react-app/src/i18n/en.json, example-react-app/src/i18n/ru.json, packages/eslint-config-jmix-react/package-lock.json, packages/jmix-addon-charts/package-lock.json, packages/jmix-addon-data-tools/package-lock.json, packages/jmix-front-generator/package-lock.json, packages/jmix-react-antd/package-lock.json, packages/jmix-react-core/package-lock.json, packages/jmix-react-web/package-lock.json, packages/jmix-rest/package-lock.json, packages/jmix-server-mock/package-lock.json, test-pup/example-react-app/defaultHotkeys/browserTable.test.js, test-pup/example-react-app/defaultHotkeys/hotkeyInfo.test.js, test-pup/example-react-app/defaultHotkeys/tabs.test.js
=> test: update hotkeys e2e tests

example-react-app/src/app/custom-data-display-components/CustomDataDisplayComponents.tsx, scripts/custom-screens/CustomDataDisplayComponents.tsx, test-pup/example-react-app/icons.test.js
=> test: add test for icons #717

example-react-app/package.json, example-react-app/src/app/header/AppHeader.module.css, example-react-app/src/app/header/AppHeader.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/header/AppHeader.module.css, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/header/AppHeader.tsx, packages/jmix-react-antd/src/ui/hotkeys/HotkeyInfoModalButton.tsx
=> feat: add navigation to header page buttons

example-react-app/package.json, packages/jmix-react-antd/src/ui/MultiSelectionTable/useMultiSelectionTable.ts
=> fix: add internationalization for MultiSelectionTable messages

packages/jmix-react-web/src/screen-registration/screen-registration.tsx
=> feat: close current screen API

example-react-app/src/dev/palette.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/dev/palette.tsx
=> chore: add FormattedMessage to palette

example-react-app/package.json, example-react-app/src/index.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/index.tsx, packages/jmix-front-generator/src/test/fixtures/react-client/src/index.tsx
=> fix: addon i18n doesn't work when using components from addon #110

packages/jmix-addon-charts/package-lock.json, packages/jmix-addon-charts/package.json, packages/jmix-addon-charts/palette.tsx, packages/jmix-addon-charts/src/component/CirclePackingChart.tsx, packages/jmix-addon-charts/src/component/HorizontalCalendarChart.tsx
affects: @haulmont/jmix-addon-charts
=> feat: add components to palette in charts addon #876

example-react-app/src/app/form-wizard-editor/FormWizardEditor.tsx, packages/jmix-front-generator/src/generators/react-typescript/entity-form-wizard/template/FormWizard.tsx.ejs, packages/jmix-react-antd/package-lock.json, packages/jmix-react-antd/src/ui/FormWizard/FormWizardManager.tsx, packages/jmix-react-antd/src/ui/FormWizard/FormWizardStep.tsx, packages/jmix-react-antd/src/ui/FormWizard/FormWizardStore.ts, packages/jmix-react-core/package-lock.json, packages/jmix-react-web/package-lock.json, packages/jmix-react-web/src/crud/editor/useEntityEditor.ts, packages/jmix-react-web/src/crud/editor/validation/extractBeanValidationErrors.ts, packages/jmix-react-web/src/index.ts, packages/jmix-rest/package-lock.json
affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-antd, @haulmont/jmix-react-web
=> fix: add client side validation to FormWizard

packages/jmix-react-core/src/app/Security.ts, packages/jmix-react-core/src/util/metadata.ts, packages/jmix-react-ui/src/ui/table/DataTable.tsx, packages/jmix-react-ui/src/ui/table/DataTableHelpers.tsx
=> feat: allow access to nested properties in data table #863

example-react-app/src/app/custom-form-controls/CustomFormControls.tsx, scripts/custom-screens/CustomFormControls.tsx, test-pup/example-react-app/user-actions.test.js
=> test: add tests for user actions #553

packages/jmix-react-ui/src/ui/table/DataTable.tsx, packages/jmix-react-ui/src/ui/table/DataTableHelpers.tsx
=> fix: clear filters error #905

packages/jmix-react-antd/src/formatters/ant_to_jmixFront.ts
=> fix: o2m composition with association field #911

example-react-app/src/app/compositionO2M-management/CompositionO2MBrowserTable.tsx, example-react-app/src/app/datatypes-test-browser-table/DatatypesTestBrowserTable.tsx, example-react-app/src/i18n/en.json, example-react-app/src/i18n/ru.json, packages/jmix-front-generator/src/building-blocks/stages/template-model/pieces/entity.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json, packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/zh_cn.json, packages/jmix-front-generator/src/test/generators/react-typrscript/common/i18n.test.ts, packages/jmix-react-antd/src/ui/table/DataTableCell.tsx
=> fix: ability to display n to many related field values in DataTable #883

packages/jmix-react-antd/src/ui/table/DataTable.tsx
=> fix: settings button position #921

packages/jmix-rest/package.json
=> fix: fix error when jmix-rest docs updates #931

packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json
=> fix: jmix packages versions in react-ts template

example-react-app/src/dev/palette.tsx, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/dev/palette.tsx
=> feat: extend palette

example-react-app/package.json, packages/jmix-react-antd/src/ui/MasterDetail/useMasterDetailEditor.tsx, packages/jmix-react-web/src/crud/editor/ui-callbacks/useSubmitCallback.ts
affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-web
=> fix: miss reactivity in submit hook

packages/jmix-react-core/src/app/MainStore.ts, packages/jmix-react-web/src/ui/IntlDocumentTitle.tsx
affects: @haulmont/jmix-react-core, @haulmont/jmix-react-web
=> fix: preserve locale change, document title localization

packages/jmix-react-antd/src/ui/form/Form.tsx
=> feat: textArea form field

packages/jmix-react-antd/src/ui/table/DataTable.module.less, packages/jmix-react-antd/src/ui/table/DataTable.tsx
=> fix: hide selection column

packages/jmix-react-web/src/index.ts, packages/jmix-react-web/src/util/copyToClipboard.ts
=> feat: copy to clipboard helper

example-react-app/src/app/associationM2M-management/AssociationM2MBrowserTable.tsx, example-react-app/src/app/associationM2O-management/AssociationM2OBrowserTable.tsx, example-react-app/src/app/associationO2M-management/AssociationO2MBrowserTable.tsx, example-react-app/src/app/associationO2O-management/AssociationO2OBrowserTable.tsx, example-react-app/src/app/boring-string-id-browser-table/BoringStringIdBrowserTable.tsx, example-react-app/src/app/car-browser-table/CarBrowserTable.tsx, example-react-app/src/app/compositionO2M-management/CompositionO2MBrowserTable.tsx, example-react-app/src/app/compositionO2O-management/CompositionO2OBrowserTable.tsx, example-react-app/src/app/datatypes-test-browser-table/DatatypesTestBrowserTable.tsx, example-react-app/src/app/deeplyNestedO2M-browser/DeeplyNestedO2MTestEntityTable.tsx, example-react-app/src/app/form-wizard-browser/FormWizardBrowserTable.tsx, example-react-app/src/app/int-id-browser-table/IntIdBrowserTable.tsx, example-react-app/src/app/int-identity-id-browser-table/IntIdentityIdBrowserTable.tsx, example-react-app/src/app/string-id-browser-table/StringIdBrowserTable.tsx, example-react-app/src/app/tricky-id-browser-table/TrickyIdBrowserTable.tsx, example-react-app/src/app/weird-string-id-browser-table/WeirdStringIdBrowserTable.tsx, packages/jmix-front-generator/src/generators/react-typescript/entity-browser/template/Table.tsx.ejs, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTable.tsx, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTableLowCase.tsx, packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/StringIdMgtTableBrowse.tsx, packages/jmix-react-antd/src/ui/form/Form.tsx
=> fix: console react warnings

packages/jmix-addon-data-tools/src/entity-inspector/entity-data-editor/composition-field/CompositionField.tsx
affects: @haulmont/jmix-addon-data-tools
=> fix: usage of getDefaultFormItemProps in addon-data-tools

example-react-app/src/themes/themes.core.ts, packages/jmix-front-generator/src/generators/react-typescript/app/template/src/themes/themes.core.ts
=> fix: respect public url in theme switcher

packages/jmix-react-antd/src/util/history.ts, packages/jmix-react-core/src/app/Router.tsx, packages/jmix-react-web/src/crud/list/useEntityList.ts, packages/jmix-react-web/src/ui/Tabs/Content.tsx
affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-core, @haulmont/jmix-react-web
=> fix: fix hash router
