Haulmont/jmix-frontend

packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json

TS in React client has been upgraded to ~4.1.3

fix(React): build error due to TS version mismatch with dependency

---

package.json
packages/jmix-react-core/src/util/metadata.ts
packages/jmix-react-ui/src/ui/table/DataTableHelpers.tsx

replace isPropertyTypeSupported() to jmix-react-core/util/metadata

refactor: replace isPropertyTypeSupported

---

packages/jmix-front-generator/src/generators/react-typescript/entity-cards/template/EntityCards.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-management-hooks/template/Cards.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-management-hooks/template/List.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-management-hooks/template/Table.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-management/template/List.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-management/template/Table.tsx.ejs
packages/jmix-front-generator/src/generators/sdk/model/entities-generation.ts
packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-cards/MpgFavoriteCarCards.tsx
packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/CarCards.tsx
packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/CarList.tsx
packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTable.tsx
packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTableLowCase.tsx
packages/jmix-front-generator/src/test/fixtures/react-client/src/app/entity-management/StringIdMgtTableBrowse.tsx
packages/jmix-react-core/src/data/Instance.tsx
packages/jmix-react-core/src/util/metadata.ts
packages/jmix-react-ui/src/ui/EntitySelectField.tsx
packages/jmix-react-ui/src/ui/table/DataTable.tsx
packages/jmix-react-ui/src/ui/table/DataTableCustomFilter.tsx
packages/jmix-rest/src/jmix.ts
packages/jmix-rest/src/util.ts
packages/jmix-rest/test/utlil.spec.js

affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-core, @haulmont/jmix-react-ui,
@haulmont/jmix-rest
BREAKING CHANGE:
added support of editing and removing entities with composite keys

feat: added support of editing and removing entities with composite keys

---

packages/jmix-front-generator/src/generators/react-typescript/entity-management-graphql-hooks/answers.ts

fix: entity management graphql template: excessive parameters

---

example-react-app/src/app/datatypes-test-browser-cards/DatatypesTestBrowserCards.tsx
example-react-app/src/app/datatypes-test-browser-list/DatatypesTestBrowserList.tsx
example-react-app/src/app/datatypes-test-browser-table/DatatypesTestBrowserTable.tsx
example-react-app/src/app/datatypes-test-cards/DatatypesTestCards.tsx
example-react-app/src/app/datatypes-test-editor/DatatypesTestEditor.tsx
packages/jmix-react-ui/src/formatters/jmixFront_to_jmixGraphQL.ts
scripts/model/graphql/datatypesTestEntity.js

fix: do not send read-only attributes in mutations #297

---

example-react-app/package.json
example-react-app/src/i18n/en.json
example-react-app/src/i18n/ru.json
packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json
packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json
packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json
packages/jmix-front-generator/src/generators/react-typescript/app/template/i18n-message-packs/zh-cn.json
packages/jmix-react-ui/src/crud/editor/validation/useAntdFormValidation.ts
packages/jmix-react-ui/src/ui/form/CompositionFields.less
packages/jmix-react-ui/src/ui/form/CompositionO2MField.tsx
packages/jmix-react-ui/src/ui/form/CompositionO2OField.less
packages/jmix-react-ui/src/ui/form/CompositionO2OField.tsx

fix: support bean validation for child entities #390

---

packages/jmix-react-ui/src/ui/menu/menu-item/MenuItem.tsx
packages/jmix-react-ui/src/ui/menu/sub-menu-item/SubMenuItem.tsx

fix: correct menuItems captions after locale changing #418

---

packages/jmix-react-ui/src/crud/list/useEntityList.ts

fix: pagination doesn't change when deleting last item #391

---

packages/jmix-react-ui/src/ui/Tabs/index.tsx

fix: get pagination params from URL #422

---

packages/jmix-front-generator/src/generators/react-typescript/app/template/src/routing.ts

fix: compilation of new project fails due to empty routing.ts #448

---

packages/jmix-react-ui/src/crud/list/useEntityList.ts

fix: entity list sends negative offset when there are no items

---

packages/jmix-react-ui/src/ui/MultiScreen/styles.less

fix: disable text wrap inside breadcrumb #416

---

packages/jmix-react-ui/src/ui/table/DataTable.test.tsx
packages/jmix-react-ui/src/ui/table/DataTable.tsx

[DataTable onRowSelectionChange event doesn't work correct](https://app.zenhub.com/workspaces/jmix-frontend-issues-5fe0992a4308f20011f1c913/issues/haulmont/jmix-frontend/373) #373

fix: onRowSelectionChange is called twice on every click on the row #373

---

packages/jmix-react-core/src/app/Screens.test.ts
packages/jmix-react-core/src/app/Screens.ts
packages/jmix-react-core/src/app/Tabs.test.ts
packages/jmix-react-core/src/app/Tabs.ts
packages/jmix-react-ui/src/crud/list/ui-callbacks/usePaginationChangeCallback.ts
packages/jmix-react-ui/src/screen-registration/screen-registration.test.tsx
packages/jmix-react-ui/src/ui/Tabs/index.tsx

refactor: remove non-null assertion operator from Screens and Tabs

---

packages/jmix-front-generator/src/init.ts

ignore client directories which doesn't contain info.json file while collecting generator clients #833

fix: collect generator clients only from dirs with info.json file

---

packages/jmix-react-antd/package.json

fix: move modules to dependencies #846

---

example-react-app/package.json
packages/jmix-addon-charts/package-lock.json
packages/jmix-addon-charts/package.json
packages/jmix-front-generator/package-lock.json
packages/jmix-front-generator/package.json
packages/jmix-front-generator/src/building-blocks/stages/writing/pieces/sdk/import-utils.ts
packages/jmix-front-generator/src/generators/react-typescript/app/template/package.json
packages/jmix-react-antd/package-lock.json
packages/jmix-react-antd/package.json
packages/jmix-react-core/package-lock.json
packages/jmix-react-core/package.json
packages/jmix-react-web/package-lock.json
packages/jmix-react-web/package.json
packages/jmix-rest/package-lock.json
packages/jmix-rest/package.json
packages/jmix-server-mock/package-lock.json
packages/jmix-server-mock/package.json

affects: eslint-config-jmix-react, @haulmont/jmix-addon-charts, @haulmont/jmix-addon-data-tools,
@haulmont/jmix-front-generator, @haulmont/jmix-react-antd, @haulmont/jmix-react-core,
@haulmont/jmix-react-web, @haulmont/jmix-rest, @haulmont/jmix-server-mock

chore: upgrade to TypeScript 4.5 #815

---

packages/jmix-front-generator/src/generators/react-typescript/entity-master-detail/template/Table.tsx.ejs
packages/jmix-front-generator/src/generators/react-typescript/entity-multi-selection-table/template/MultiSelectionTable.tsx.ejs

fix: filter recurtion relations in generated graphQL list queries

---

packages/jmix-react-web/src/hotkeys/useHotkey.ts

fix: useScreenHotkey hook doesnt break without screen-api

---

example-react-app/package.json
packages/jmix-react-antd/package-lock.json
packages/jmix-react-antd/src/i18n/I18nProvider.tsx
packages/jmix-react-antd/src/i18n/intl.tsx
packages/jmix-react-antd/src/index.ts
packages/jmix-react-core/package-lock.json
packages/jmix-react-core/src/app/JmixAppProvider.tsx
packages/jmix-react-core/src/app/MainStore.ts
packages/jmix-react-web/package-lock.json
packages/jmix-rest/package-lock.json

affects: @haulmont/jmix-react-antd, @haulmont/jmix-react-core, @haulmont/jmix-react-web,
@haulmont/jmix-rest

feat: add ability to use intl API outside of React components #859

---

packages/jmix-react-antd/src/ui/table/DataTable.tsx

fix: enabling field settings in DataTable breaks row selection #919

---

packages/jmix-front-generator/src/common/studio/studio-integration.ts

chore: rename Cuba to Jmix #804

---

packages/jmix-react-antd/src/ui/form/Form.tsx

fix: fields of Date(Time) type don't inherit global formatting rules
